baseURL = 'https://peihuanni.github.io/'
languageCode = 'en-us'
title = 'Peihuan Ni'
theme = 'ananke'


[params.ananke.social.follow]
networks = ["github"]

[params.ananke.social.github]
username = "PeihuanNi"

[menu]
    [[menu.main]]
        identifier = "about"
        name = "About Me"
        url = "/about/"
        weight = 1

    [[menu.main]]
        identifier = "publications"
        name = "Publications"
        url = "/publications/"
        weight = 2

    [[menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/projects/"
        weight = 3